### ISSUE TITLE
Notebooks corrupt?

### ISSUE THREAD

**Issue by indielyt** [microsoft/Cognitive-Vision-Python#24]
I'm having trouble viewing these notebooks on Github.  Downloading the repository and trying to open the notebooks locally is returning the following error: 

Unreadable Notebook: Y:\pdata\174741\Project Info\Python_Scripts\misc\Cognitive-Vision-Python-master\Cognitive-Vision-Python-master\Jupyter Notebook\Computer Vision API Example.ipynb NotJSONError('Notebook does not appear to be JSON: \'{\\n "cells": [\\n {\\n "cell_type": "m...')

**Comment by ashish2303** [comment]
i am also getting same error . if possible please upload jupyter notebook file again
