### ISSUE TITLE
jupyter notebook files are corrupt 

### ISSUE THREAD

**Issue by ashish2303** [microsoft/Cognitive-Vision-Python#25]
Hi Team ,
can you please upload fresh jupyter notebook files as existing files are not opening . it would be great help . thanks in advance

**Comment by xfil** [comment]
Hi, I am having the same problem, I get the following error:
Unreadable Notebook: ...\MS-py\Computer Vision API Example.ipynb NotJSONError('Notebook does not appear to be JSON: \'{\\n "cells": [\\n {\\n "cell_type": "m...')
Thanks for any hel
